# Making an array with ones

In [492]:
import numpy
w = numpy.ones([5,5],dtype=numpy.int8)

h=int(w.shape[0]/2)
r=int(w.shape[1]/2)

print(h,r)
print(w[h,r])

w[h][r]=0
print(w)

2 2
1
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 0 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [493]:
# Explained above code
import numpy

w = numpy.ones([5,5], dtype=numpy.int8)  # Create a 5x5 array of ones (int8 type)

h = int(w.shape[0] / 2)  # h = 2 (center row)
r = int(w.shape[1] / 2)  # r = 2 (center column)

print(h, r)              # Should print: 2 2
print(w[h, r])           # Should print: 1 (center value)

w[h][r] = 0              # Set center value to 0
print(w)                 # Should print the matrix with center value set to 0


2 2
1
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 0 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


# Practicing forward pass

In [494]:
import torch 
import torch.nn as nn

def binary_cross_entropy_loss(y_true, y_pred):
    # Ensure predicted values are in the range [0, 1]
    epsilon=1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)  # Avoid log(0) issues
    loss = -(y_true * torch.log(y_pred) + (1 - y_true) * torch.log(1 - y_pred))
    return loss

# Initaial Parameters
x = torch.tensor(5.5)
y = torch.tensor(0)

# Parameters with gradients
w = torch.tensor(1.0, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)

In [495]:
epochs=300
lr=0.01

for epoch in range(1, epochs+1):
    z = x * w + b
    y_pred = torch.sigmoid(z)
    loss = binary_cross_entropy_loss(y,y_pred)
    loss.backward()    
    print(epoch, loss.item())

    with torch.no_grad():  # Perform manual gradient descent
        w -= lr * w.grad
        b -= lr * b.grad

    w.grad.zero_()  # Reset gradients
    b.grad.zero_()

    


1 5.504086971282959
2 5.194328308105469
3 4.885583877563477
4 4.578197479248047
5 4.272622585296631
6 3.969496965408325
7 3.669649600982666
8 3.3741464614868164
9 3.084341526031494
10 2.8019165992736816
11 2.5288779735565186
12 2.267523765563965
13 2.02032470703125
14 1.7897261381149292
15 1.577878475189209
16 1.3863532543182373
17 1.2159124612808228
18 1.0664112567901611
19 0.9368649125099182
20 0.8256462812423706
21 0.7307476997375488
22 0.6500300168991089
23 0.5814123749732971
24 0.5229921936988831
25 0.4731002449989319
26 0.4303135573863983
27 0.39344149827957153
28 0.3614991307258606
29 0.33367666602134705
30 0.3093107044696808
31 0.28785765171051025
32 0.26887133717536926
33 0.251984566450119
34 0.23689404129981995
35 0.22334808111190796
36 0.21113687753677368
37 0.2000848650932312
38 0.19004417955875397
39 0.18088994920253754
40 0.17251580953598022
41 0.16483114659786224
42 0.15775837004184723
43 0.15123048424720764
44 0.14518964290618896
45 0.139585480093956
46 0.13437438011169

In [497]:
z = w*x+b
y_pred = torch.sigmoid(z)
y_pred

tensor(0.0117, grad_fn=<SigmoidBackward0>)

# ANN

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class SimpleANN(nn.Module):
    def __init__(self):
        super(SimpleANN, self).__init__()
        
        # Input size = 784 (for MNIST: 28x28 images flattened)
        self.fc1 = nn.Linear(784, 256)
        self.fc2 = nn.Linear(256, 128)
        self.fc3 = nn.Linear(128, 10)  # 10 classes for classification

        # Optional dropout
        self.dropout = nn.Dropout(0.5)

    def forward(self, x):
        x = x.view(-1, 784)          # Flatten image to 784-dim vector
        x = F.relu(self.fc1(x))      # Hidden layer 1
        x = self.dropout(x)          # Dropout for regularization
        x = F.relu(self.fc2(x))      # Hidden layer 2
        x = self.fc3(x)              # Output layer (logits)
        return x


#############

In [18]:
class cnn(nn.Module):
    def init(super):
        self.conv1 = nn.conv2d(4,1,padding = 3,strider = 1)    
        self.pool = nn.MaxPool2d(2,2)
        self.fc = nn.Linear(2*12)
        return(x)

